void myExit();
void menuReadDriveStatus();
void menuEnumerateDrives();
void menuShow();
void menuInitializeDrive();
void menuReadCMDGetPartition();
void menuChangeCMDPartition();
void menuDirectDiskCommand();
void menuCMDPartitionDirectory();